### PR TITLE
(fix): #INC-5312: Missing image #2

### PR DESCRIPTION
**Pull request by yawerijaz**
# Description

Display placeholder image when user did not supply an image.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @yawerijaz, I'll review the changes right away!

**Comment by yawerijaz** [comment]
image

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @yawerijaz! You're now able to merge the PR.

**Pull request merged**
